version: "3.7"

services:
  ##########################################################################
  ######                       HUNTING SERVER                        #######
  ##########################################################################
  hunting-server:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/sh -c "
      poetry run uvicorn app.main:app --reload --host 0.0.0.0;
      "      
    volumes:
      - .:/app  
    env_file:
      - .env
    networks:
      - hunting

networks:
  hunting: