FROM python:3.9.16-buster

WORKDIR /app

ENV POETRY_VERSION=1.5.1

# Install Poetry
RUN curl -sSL  https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
    export PATH="/opt/poetry/bin:$PATH" && \
    poetry config virtualenvs.create false

# Copy poetry.lock* in case it doesn't exist in the repo
COPY ./pyproject.toml ./poetry.lock* /

# Allow installing dev dependencies to run tests
ARG INSTALL_DEV=false
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then /opt/poetry/bin/poetry install --no-root ; else /opt/poetry/bin/poetry install --no-root --no-dev ; fi"

COPY . .
ENV PYTHONPATH=/app