version: "3.7"

services:

  ##########################################################################
  ######                      BACKGROUND TASKS                       #######
  ##########################################################################

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: >
      /bin/sh -c "
      redis-server --appendonly yes --requirepass password
      "
    networks:
      - hunting

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      /bin/sh -c "
      celery -A app.worker worker -l info --max-memory-per-child=3000000 --max-tasks-per-child=2;
      "
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - hunting
    extra_hosts:
    - "host.docker.internal:host-gateway"

  flower:
    build: 
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/sh -c "
      celery -A app.worker flower --port=5555
      "
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://:password@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:password@redis:6379/0
      - FLOWER_UNAUTHENTICATED_API=true
    depends_on:
      - redis
      - celery
    networks:
      - hunting

  ##########################################################################
  ######                           DATABASES                         #######
  ##########################################################################
  mongodb:
    image: mongo:6.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./volumes/mongodb:/data/db
    ports: 
      - 27017:27017
    networks:
      - hunting

  ##########################################################################
  ######                       HUNTING SERVER                        #######
  ##########################################################################
  hunting-server:
    ports:
      - 8002:8000
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/sh -c "
      uvicorn app.main:app --reload --host 0.0.0.0;
      "      
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - hunting
    extra_hosts:
    - "host.docker.internal:host-gateway"


networks:
  hunting: