version: "3.7"

services:

  ##########################################################################
  ######                             CACHE                           #######
  ##########################################################################

  redis:
    image: redis:alpine
    ports:
      - 6379:6379    
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes --requirepass redispass
    networks:
      - hunting

  ##########################################################################
  ######                       HUNTING SERVER                        #######
  ##########################################################################
  hunting-server:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      /bin/sh -c "
      poetry run uvicorn app.main:app --reload --host 0.0.0.0;
      "      
    volumes:
      - .:/app  
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - hunting

networks:
  hunting: