[tool.poetry]
name = "hunting"
version = "0.1.0"
description = "Hunting is Pandas profiling exposed as REST API"
authors = ["Factly Media & Research"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.70.0"
uvicorn = "^0.15.0"
pandas = "^1.3.3"
pandas-profiling = "^3.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
